---
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - errorlint
    - misspell

  settings:
    errcheck:
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log

  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

formatters:
  enable:
    - gofumpt
    - goimports

  settings:
    gofumpt:
      extra-rules: true

issues:
  # Maximum issues count per one linter.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  max-same-issues: 0
