---
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - misspell

  settings:
    errcheck:
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log

  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

formatters:
  enable:
    - gofumpt
    - goimports

  settings:
    gofumpt:
      extra-rules: true
