module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.14

require (
	github.com/golangci/golangci-lint v1.27.0 // cmd/golangci-lint
	github.com/securego/gosec v0.0.0-20200316084457-7da9f46445fd // indirect
)
