// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package testpb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type PingRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	SleepTimeMs          int32    `protobuf:"varint,2,opt,name=sleep_time_ms,json=sleepTimeMs,proto3" json:"sleep_time_ms,omitempty"`
	ErrorCodeReturned    uint32   `protobuf:"varint,3,opt,name=error_code_returned,json=errorCodeReturned,proto3" json:"error_code_returned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *PingRequest) GetSleepTimeMs() int32 {
	if m != nil {
		return m.SleepTimeMs
	}
	return 0
}

func (m *PingRequest) GetErrorCodeReturned() uint32 {
	if m != nil {
		return m.ErrorCodeReturned
	}
	return 0
}

type PingResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Counter              int32    `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *PingResponse) GetCounter() int32 {
	if m != nil {
		return m.Counter
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "grpc_middleware.testpb.Empty")
	proto.RegisterType((*PingRequest)(nil), "grpc_middleware.testpb.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "grpc_middleware.testpb.PingResponse")
}

func init() {
	proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e)
}

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4d, 0x4b, 0x33, 0x31,
	0x10, 0xc7, 0x9b, 0xa7, 0x4f, 0xad, 0x9d, 0xb5, 0x07, 0xa3, 0xc8, 0x22, 0x08, 0x25, 0x7a, 0xd8,
	0x53, 0x2c, 0x7a, 0xf7, 0xa0, 0x78, 0x53, 0xd0, 0xb4, 0x08, 0x0a, 0xb2, 0xb4, 0xbb, 0x43, 0x09,
	0x34, 0x9b, 0x98, 0x64, 0x5b, 0xfc, 0x7c, 0x7e, 0x31, 0x49, 0xba, 0x42, 0x0f, 0x5a, 0x7a, 0xe8,
	0x71, 0xe6, 0x17, 0xfe, 0x2f, 0x43, 0x00, 0x3c, 0x3a, 0xcf, 0x8d, 0xd5, 0x5e, 0xd3, 0x93, 0x99,
	0x35, 0x45, 0xae, 0x64, 0x59, 0xce, 0x71, 0x39, 0xb1, 0xc8, 0x03, 0x33, 0x53, 0xd6, 0x85, 0xce,
	0xbd, 0x32, 0xfe, 0x93, 0x2d, 0x21, 0x79, 0x92, 0xd5, 0x4c, 0xe0, 0x47, 0x8d, 0xce, 0xd3, 0x63,
	0xe8, 0x2c, 0x26, 0xf3, 0x1a, 0x53, 0x32, 0x20, 0x59, 0x4f, 0xac, 0x06, 0xca, 0xa0, 0xef, 0xe6,
	0x88, 0x26, 0xf7, 0x52, 0x61, 0xae, 0x5c, 0xfa, 0x6f, 0x40, 0xb2, 0x8e, 0x48, 0xe2, 0x72, 0x2c,
	0x15, 0x3e, 0x3a, 0xca, 0xe1, 0x08, 0xad, 0xd5, 0x36, 0x2f, 0x74, 0x89, 0xb9, 0x45, 0x5f, 0xdb,
	0x0a, 0xcb, 0xb4, 0x3d, 0x20, 0x59, 0x5f, 0x1c, 0x46, 0x74, 0xa7, 0x4b, 0x14, 0x0d, 0x60, 0x37,
	0x70, 0xb0, 0x32, 0x76, 0x46, 0x57, 0x0e, 0x83, 0xf3, 0xcb, 0xba, 0x73, 0x1c, 0x68, 0x0a, 0xdd,
	0x42, 0xd7, 0x95, 0x47, 0xdb, 0x78, 0xfe, 0x8c, 0x57, 0x5f, 0x6d, 0x48, 0xc6, 0xe8, 0xfc, 0x08,
	0xed, 0x42, 0x16, 0x48, 0x05, 0xf4, 0x82, 0x5e, 0x6c, 0x45, 0xcf, 0xf8, 0xef, 0xbd, 0x79, 0xc4,
	0xa7, 0x17, 0x7f, 0xe1, 0xf5, 0x44, 0xac, 0x45, 0x47, 0xf0, 0x3f, 0x6c, 0xe8, 0xf9, 0xe6, 0xf7,
	0xf1, 0x74, 0x5b, 0x8b, 0x3e, 0x37, 0x41, 0xc3, 0x45, 0xb6, 0x53, 0xde, 0xdc, 0x86, 0xb5, 0xe8,
	0x2b, 0xec, 0x87, 0xf7, 0x0f, 0xd2, 0xf9, 0x9d, 0x66, 0x1d, 0x12, 0xfa, 0x0e, 0x10, 0x76, 0x23,
	0x6f, 0x71, 0xa2, 0x76, 0x2a, 0x9e, 0x91, 0x21, 0xb9, 0x4d, 0xde, 0x7a, 0x9c, 0x5f, 0xae, 0xf8,
	0x74, 0x2f, 0xfe, 0xd9, 0xeb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x74, 0x48, 0x5f, 0xc1,
	0x02, 0x00, 0x00,
}
