// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fields.proto

//  This file is used for grpctesting discovery of log fields from requests using reflection and gogo proto more tags.

package gogotestpb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Metadata struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty" log_field:"meta_tags"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_d39ad626ec0e575e, []int{0}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type PingId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" log_field:"ping_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingId) Reset()         { *m = PingId{} }
func (m *PingId) String() string { return proto.CompactTextString(m) }
func (*PingId) ProtoMessage()    {}
func (*PingId) Descriptor() ([]byte, []int) {
	return fileDescriptor_d39ad626ec0e575e, []int{1}
}
func (m *PingId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingId.Unmarshal(m, b)
}
func (m *PingId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingId.Marshal(b, m, deterministic)
}
func (m *PingId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingId.Merge(m, src)
}
func (m *PingId) XXX_Size() int {
	return xxx_messageInfo_PingId.Size(m)
}
func (m *PingId) XXX_DiscardUnknown() {
	xxx_messageInfo_PingId.DiscardUnknown(m)
}

var xxx_messageInfo_PingId proto.InternalMessageInfo

func (m *PingId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Ping struct {
	Id                   *PingId  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_d39ad626ec0e575e, []int{2}
}
func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetId() *PingId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Ping) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PingRequest struct {
	Ping                 *Ping     `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	Meta                 *Metadata `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d39ad626ec0e575e, []int{3}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetPing() *Ping {
	if m != nil {
		return m.Ping
	}
	return nil
}

func (m *PingRequest) GetMeta() *Metadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Pong struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" log_field:"pong_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_d39ad626ec0e575e, []int{4}
}
func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PongRequest struct {
	Pong                 *Pong     `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	Meta                 *Metadata `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PongRequest) Reset()         { *m = PongRequest{} }
func (m *PongRequest) String() string { return proto.CompactTextString(m) }
func (*PongRequest) ProtoMessage()    {}
func (*PongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d39ad626ec0e575e, []int{5}
}
func (m *PongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongRequest.Unmarshal(m, b)
}
func (m *PongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongRequest.Marshal(b, m, deterministic)
}
func (m *PongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongRequest.Merge(m, src)
}
func (m *PongRequest) XXX_Size() int {
	return xxx_messageInfo_PongRequest.Size(m)
}
func (m *PongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PongRequest proto.InternalMessageInfo

func (m *PongRequest) GetPong() *Pong {
	if m != nil {
		return m.Pong
	}
	return nil
}

func (m *PongRequest) GetMeta() *Metadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

type OneOfLogField struct {
	// Types that are valid to be assigned to Identifier:
	//	*OneOfLogField_BarId
	//	*OneOfLogField_BazId
	Identifier           isOneOfLogField_Identifier `protobuf_oneof:"identifier"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *OneOfLogField) Reset()         { *m = OneOfLogField{} }
func (m *OneOfLogField) String() string { return proto.CompactTextString(m) }
func (*OneOfLogField) ProtoMessage()    {}
func (*OneOfLogField) Descriptor() ([]byte, []int) {
	return fileDescriptor_d39ad626ec0e575e, []int{6}
}
func (m *OneOfLogField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneOfLogField.Unmarshal(m, b)
}
func (m *OneOfLogField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneOfLogField.Marshal(b, m, deterministic)
}
func (m *OneOfLogField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneOfLogField.Merge(m, src)
}
func (m *OneOfLogField) XXX_Size() int {
	return xxx_messageInfo_OneOfLogField.Size(m)
}
func (m *OneOfLogField) XXX_DiscardUnknown() {
	xxx_messageInfo_OneOfLogField.DiscardUnknown(m)
}

var xxx_messageInfo_OneOfLogField proto.InternalMessageInfo

type isOneOfLogField_Identifier interface {
	isOneOfLogField_Identifier()
}

type OneOfLogField_BarId struct {
	BarId string `protobuf:"bytes,1,opt,name=bar_id,json=barId,proto3,oneof" json:"bar_id,omitempty" log_field:"bar_id"`
}
type OneOfLogField_BazId struct {
	BazId string `protobuf:"bytes,2,opt,name=baz_id,json=bazId,proto3,oneof" json:"baz_id,omitempty" log_field:"baz_id"`
}

func (*OneOfLogField_BarId) isOneOfLogField_Identifier() {}
func (*OneOfLogField_BazId) isOneOfLogField_Identifier() {}

func (m *OneOfLogField) GetIdentifier() isOneOfLogField_Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *OneOfLogField) GetBarId() string {
	if x, ok := m.GetIdentifier().(*OneOfLogField_BarId); ok {
		return x.BarId
	}
	return ""
}

func (m *OneOfLogField) GetBazId() string {
	if x, ok := m.GetIdentifier().(*OneOfLogField_BazId); ok {
		return x.BazId
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OneOfLogField) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OneOfLogField_BarId)(nil),
		(*OneOfLogField_BazId)(nil),
	}
}

type GoGoProtoStdTime struct {
	Timestamp            *time.Time `protobuf:"bytes,1,opt,name=timestamp,proto3,stdtime" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GoGoProtoStdTime) Reset()         { *m = GoGoProtoStdTime{} }
func (m *GoGoProtoStdTime) String() string { return proto.CompactTextString(m) }
func (*GoGoProtoStdTime) ProtoMessage()    {}
func (*GoGoProtoStdTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_d39ad626ec0e575e, []int{7}
}
func (m *GoGoProtoStdTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoGoProtoStdTime.Unmarshal(m, b)
}
func (m *GoGoProtoStdTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoGoProtoStdTime.Marshal(b, m, deterministic)
}
func (m *GoGoProtoStdTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoGoProtoStdTime.Merge(m, src)
}
func (m *GoGoProtoStdTime) XXX_Size() int {
	return xxx_messageInfo_GoGoProtoStdTime.Size(m)
}
func (m *GoGoProtoStdTime) XXX_DiscardUnknown() {
	xxx_messageInfo_GoGoProtoStdTime.DiscardUnknown(m)
}

var xxx_messageInfo_GoGoProtoStdTime proto.InternalMessageInfo

func (m *GoGoProtoStdTime) GetTimestamp() *time.Time {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*Metadata)(nil), "grpc_middleware.gogotestpb.Metadata")
	proto.RegisterType((*PingId)(nil), "grpc_middleware.gogotestpb.PingId")
	proto.RegisterType((*Ping)(nil), "grpc_middleware.gogotestpb.Ping")
	proto.RegisterType((*PingRequest)(nil), "grpc_middleware.gogotestpb.PingRequest")
	proto.RegisterType((*Pong)(nil), "grpc_middleware.gogotestpb.Pong")
	proto.RegisterType((*PongRequest)(nil), "grpc_middleware.gogotestpb.PongRequest")
	proto.RegisterType((*OneOfLogField)(nil), "grpc_middleware.gogotestpb.OneOfLogField")
	proto.RegisterType((*GoGoProtoStdTime)(nil), "grpc_middleware.gogotestpb.GoGoProtoStdTime")
}

func init() { proto.RegisterFile("fields.proto", fileDescriptor_d39ad626ec0e575e) }

var fileDescriptor_d39ad626ec0e575e = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcf, 0xaa, 0xd3, 0x40,
	0x14, 0x87, 0x6f, 0x6a, 0x5a, 0xec, 0xe9, 0x15, 0x2e, 0xe3, 0x55, 0x6b, 0x17, 0xa6, 0x0c, 0x82,
	0xdd, 0x98, 0x60, 0x75, 0xa1, 0x2e, 0x5c, 0x64, 0xe1, 0xb5, 0xa0, 0xdc, 0x32, 0xde, 0x95, 0x9b,
	0x30, 0x71, 0xa6, 0xc3, 0x40, 0x92, 0x13, 0x93, 0xa9, 0x42, 0x41, 0x7c, 0x05, 0x97, 0x3e, 0x5d,
	0x5d, 0xf8, 0x06, 0x7d, 0x02, 0x99, 0x49, 0xff, 0x44, 0xa4, 0x2a, 0xb8, 0x9b, 0x61, 0x7e, 0xdf,
	0x99, 0xef, 0x1c, 0x0e, 0x9c, 0x2e, 0xb4, 0xcc, 0x44, 0x1d, 0x96, 0x15, 0x1a, 0x24, 0x23, 0x55,
	0x95, 0xef, 0x93, 0x5c, 0x0b, 0x91, 0xc9, 0x4f, 0xbc, 0x92, 0xa1, 0x42, 0x85, 0x46, 0xd6, 0xa6,
	0x4c, 0x47, 0xe7, 0xf6, 0xec, 0x62, 0x91, 0x3d, 0x35, 0xc4, 0x28, 0x50, 0x88, 0x2a, 0x93, 0x91,
	0xbb, 0xa5, 0xcb, 0x45, 0x64, 0x74, 0x2e, 0x6b, 0xc3, 0xf3, 0xb2, 0x09, 0xd0, 0x67, 0x70, 0xfd,
	0x8d, 0x34, 0x5c, 0x70, 0xc3, 0xc9, 0x43, 0xf0, 0x0d, 0x57, 0xf5, 0xd0, 0x1b, 0x5f, 0x9b, 0xf4,
	0xe3, 0xbb, 0x9b, 0x75, 0x70, 0x2b, 0x43, 0x95, 0x38, 0x85, 0xe7, 0x34, 0x97, 0x86, 0x27, 0xf6,
	0x9d, 0x32, 0x17, 0xa3, 0x8f, 0xa0, 0x37, 0xd7, 0x85, 0x9a, 0x09, 0xf2, 0x00, 0x3a, 0x5a, 0x0c,
	0xbd, 0xb1, 0x37, 0xe9, 0xc6, 0x77, 0x36, 0xeb, 0xe0, 0x66, 0x0b, 0x2b, 0x75, 0xa1, 0x12, 0x2d,
	0x28, 0xeb, 0x68, 0x41, 0xe7, 0xe0, 0x5b, 0x84, 0x4c, 0xf7, 0xc0, 0x60, 0x4a, 0xc3, 0xe3, 0x5d,
	0x85, 0xcd, 0x07, 0x96, 0x25, 0xe7, 0xd0, 0xfd, 0xc8, 0xb3, 0xa5, 0x1c, 0x76, 0xc6, 0xde, 0xa4,
	0xcf, 0x9a, 0x0b, 0xfd, 0x0c, 0x03, 0x9b, 0x61, 0xf2, 0xc3, 0x52, 0xd6, 0x86, 0x3c, 0x01, 0xdf,
	0x7e, 0xb8, 0x2d, 0x3d, 0xfe, 0x5b, 0x69, 0xe6, 0xd2, 0xe4, 0x29, 0xf8, 0xb6, 0x3b, 0x57, 0x79,
	0x30, 0xbd, 0xff, 0x27, 0x6a, 0x37, 0x2c, 0xe6, 0x08, 0x1a, 0x81, 0x3f, 0xc7, 0x42, 0xb5, 0x26,
	0xd0, 0xff, 0x7d, 0x02, 0xd8, 0x9a, 0x80, 0xf5, 0xc5, 0x5f, 0x7d, 0xf1, 0x1f, 0x7d, 0xd1, 0xf9,
	0xe2, 0x7f, 0xf9, 0x7e, 0x81, 0x1b, 0x97, 0x85, 0xbc, 0x5c, 0xbc, 0x46, 0xf5, 0xd2, 0xda, 0x91,
	0x08, 0x7a, 0x29, 0xaf, 0x92, 0xbd, 0xfc, 0xed, 0xcd, 0x3a, 0x20, 0x2d, 0xf9, 0xe6, 0x91, 0xbe,
	0x3a, 0x61, 0xdd, 0x94, 0x57, 0xb3, 0x2d, 0xb0, 0xb2, 0x40, 0xe7, 0x08, 0xb0, 0x3a, 0x00, 0xab,
	0x99, 0x88, 0x4f, 0x01, 0xb4, 0x90, 0x85, 0xd1, 0x0b, 0x2d, 0x2b, 0xca, 0xe0, 0xec, 0x02, 0x2f,
	0x70, 0x6e, 0x97, 0xef, 0xad, 0x11, 0x57, 0x3a, 0x97, 0xe4, 0x05, 0xf4, 0xf7, 0x6b, 0xb9, 0x9d,
	0xc4, 0x28, 0x6c, 0x16, 0x37, 0xdc, 0x2d, 0x6e, 0x78, 0xb5, 0x4b, 0xc4, 0xfe, 0xd7, 0xef, 0x81,
	0xc7, 0x0e, 0x48, 0x7c, 0xf6, 0xed, 0xc7, 0xbd, 0x93, 0x77, 0x70, 0xe8, 0x3a, 0xed, 0x39, 0xec,
	0xf1, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x9a, 0xee, 0xac, 0x3f, 0x03, 0x00, 0x00,
}
