// Code generated by protoc-gen-gogo.
// source: fields.proto
// DO NOT EDIT!

/*
Package mwitkow_testproto is a generated protocol buffer package.

It is generated from these files:
	fields.proto

It has these top-level messages:
	Metadata
	PingId
	Ping
	PingRequest
	Pong
	PongRequest
*/
package mwitkow_testproto

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Metadata struct {
	Tags []string `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty" log_field:"meta_tags"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptorFields, []int{0} }

type PingId struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" log_field:"ping_id"`
}

func (m *PingId) Reset()                    { *m = PingId{} }
func (m *PingId) String() string            { return proto.CompactTextString(m) }
func (*PingId) ProtoMessage()               {}
func (*PingId) Descriptor() ([]byte, []int) { return fileDescriptorFields, []int{1} }

type Ping struct {
	Id    *PingId `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Value string  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptorFields, []int{2} }

func (m *Ping) GetId() *PingId {
	if m != nil {
		return m.Id
	}
	return nil
}

type PingRequest struct {
	Ping *Ping     `protobuf:"bytes,1,opt,name=ping" json:"ping,omitempty"`
	Meta *Metadata `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptorFields, []int{3} }

func (m *PingRequest) GetPing() *Ping {
	if m != nil {
		return m.Ping
	}
	return nil
}

func (m *PingRequest) GetMeta() *Metadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Pong struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" log_field:"pong_id"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptorFields, []int{4} }

type PongRequest struct {
	Pong *Pong     `protobuf:"bytes,1,opt,name=pong" json:"pong,omitempty"`
	Meta *Metadata `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
}

func (m *PongRequest) Reset()                    { *m = PongRequest{} }
func (m *PongRequest) String() string            { return proto.CompactTextString(m) }
func (*PongRequest) ProtoMessage()               {}
func (*PongRequest) Descriptor() ([]byte, []int) { return fileDescriptorFields, []int{5} }

func (m *PongRequest) GetPong() *Pong {
	if m != nil {
		return m.Pong
	}
	return nil
}

func (m *PongRequest) GetMeta() *Metadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*Metadata)(nil), "mwitkow.testproto.Metadata")
	proto.RegisterType((*PingId)(nil), "mwitkow.testproto.PingId")
	proto.RegisterType((*Ping)(nil), "mwitkow.testproto.Ping")
	proto.RegisterType((*PingRequest)(nil), "mwitkow.testproto.PingRequest")
	proto.RegisterType((*Pong)(nil), "mwitkow.testproto.Pong")
	proto.RegisterType((*PongRequest)(nil), "mwitkow.testproto.PongRequest")
}

func init() { proto.RegisterFile("fields.proto", fileDescriptorFields) }

var fileDescriptorFields = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x50, 0xb1, 0x4e, 0xf3, 0x30,
	0x18, 0x54, 0xfa, 0xa7, 0xd5, 0x5f, 0x87, 0x05, 0x03, 0x6a, 0x0a, 0x43, 0x23, 0x2f, 0x04, 0xa1,
	0x26, 0xa2, 0x4c, 0x30, 0x76, 0x41, 0x0c, 0x48, 0x95, 0x5f, 0x20, 0x72, 0xb0, 0x6b, 0xac, 0x26,
	0xf9, 0x0a, 0x71, 0xe8, 0xdb, 0xf6, 0x21, 0xfa, 0x04, 0xc8, 0x5f, 0x00, 0x05, 0x15, 0x18, 0xd8,
	0x72, 0x97, 0xbb, 0xfb, 0xee, 0x4c, 0x0e, 0x96, 0x46, 0x15, 0xb2, 0x4e, 0xd6, 0x2f, 0x60, 0x81,
	0x1e, 0x96, 0x1b, 0x63, 0x57, 0xb0, 0x49, 0xac, 0xaa, 0x2d, 0x52, 0xa7, 0x53, 0x6d, 0xec, 0x53,
	0x93, 0x27, 0x8f, 0x50, 0xa6, 0x1a, 0x34, 0xa4, 0x48, 0xe7, 0xcd, 0x12, 0x11, 0x02, 0xfc, 0x6a,
	0x13, 0xd8, 0x0d, 0xf9, 0xff, 0xa0, 0xac, 0x90, 0xc2, 0x0a, 0x3a, 0x25, 0xbe, 0x15, 0xba, 0x0e,
	0xbd, 0xe8, 0x5f, 0x3c, 0x9c, 0x8f, 0x77, 0xdb, 0xc9, 0x49, 0x01, 0x3a, 0xc3, 0x8b, 0xb7, 0xac,
	0x54, 0x56, 0x64, 0xee, 0x3f, 0xe3, 0x28, 0x63, 0x57, 0x64, 0xb0, 0x30, 0x95, 0xbe, 0x97, 0xf4,
	0x9c, 0xf4, 0x8c, 0x0c, 0xbd, 0xc8, 0x8b, 0xfb, 0xf3, 0xd1, 0x6e, 0x3b, 0x39, 0xea, 0xd8, 0xd6,
	0xa6, 0xd2, 0x99, 0x91, 0x8c, 0xf7, 0x8c, 0x64, 0x77, 0xc4, 0x77, 0x16, 0x7a, 0xf1, 0x69, 0x08,
	0x66, 0xe3, 0x64, 0x6f, 0x44, 0xd2, 0xe6, 0x3a, 0x0b, 0x3d, 0x26, 0xfd, 0x57, 0x51, 0x34, 0x2a,
	0xec, 0x45, 0x5e, 0x3c, 0xe4, 0x2d, 0x60, 0x2b, 0x12, 0x38, 0x0d, 0x57, 0xcf, 0x8d, 0xaa, 0x2d,
	0xbd, 0x24, 0xbe, 0xbb, 0xf3, 0x9e, 0x38, 0xfa, 0x21, 0x91, 0xa3, 0x88, 0xa6, 0xc4, 0x77, 0x5b,
	0x30, 0x30, 0x98, 0x9d, 0x7d, 0x23, 0xfe, 0x78, 0x11, 0x8e, 0x42, 0x96, 0x12, 0x7f, 0x01, 0x95,
	0xee, 0xcc, 0x1c, 0xee, 0xcf, 0x84, 0xce, 0x4c, 0xd7, 0x0e, 0xbe, 0xb6, 0x83, 0xdf, 0xdb, 0x01,
	0xb6, 0x83, 0x3f, 0xb4, 0xcb, 0x07, 0xc8, 0x5e, 0xbf, 0x05, 0x00, 0x00, 0xff, 0xff, 0x83, 0xa3,
	0xad, 0x77, 0x1a, 0x02, 0x00, 0x00,
}
