// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: testing/testvalidate/v1/test_validate.proto

package testvalidatev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_testing_testvalidate_v1_test_validate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testing_testvalidate_v1_test_validate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_testing_testvalidate_v1_test_validate_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_testing_testvalidate_v1_test_validate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testing_testvalidate_v1_test_validate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_testing_testvalidate_v1_test_validate_proto_rawDescGZIP(), []int{1}
}

type SendStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendStreamRequest) Reset() {
	*x = SendStreamRequest{}
	mi := &file_testing_testvalidate_v1_test_validate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStreamRequest) ProtoMessage() {}

func (x *SendStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testing_testvalidate_v1_test_validate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStreamRequest.ProtoReflect.Descriptor instead.
func (*SendStreamRequest) Descriptor() ([]byte, []int) {
	return file_testing_testvalidate_v1_test_validate_proto_rawDescGZIP(), []int{2}
}

func (x *SendStreamRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendStreamResponse) Reset() {
	*x = SendStreamResponse{}
	mi := &file_testing_testvalidate_v1_test_validate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStreamResponse) ProtoMessage() {}

func (x *SendStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testing_testvalidate_v1_test_validate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStreamResponse.ProtoReflect.Descriptor instead.
func (*SendStreamResponse) Descriptor() ([]byte, []int) {
	return file_testing_testvalidate_v1_test_validate_proto_rawDescGZIP(), []int{3}
}

var File_testing_testvalidate_v1_test_validate_proto protoreflect.FileDescriptor

const file_testing_testvalidate_v1_test_validate_proto_rawDesc = "" +
	"\n" +
	"+testing/testvalidate/v1/test_validate.proto\x12\x17testing.testvalidate.v1\x1a\x1bbuf/validate/validate.proto\"0\n" +
	"\vSendRequest\x12!\n" +
	"\amessage\x18\x01 \x01(\tB\a\xbaH\x04r\x02`\x01R\amessage\"\x0e\n" +
	"\fSendResponse\"6\n" +
	"\x11SendStreamRequest\x12!\n" +
	"\amessage\x18\x01 \x01(\tB\a\xbaH\x04r\x02`\x01R\amessage\"\x14\n" +
	"\x12SendStreamResponse2\xd7\x01\n" +
	"\x13TestValidateService\x12U\n" +
	"\x04Send\x12$.testing.testvalidate.v1.SendRequest\x1a%.testing.testvalidate.v1.SendResponse\"\x00\x12i\n" +
	"\n" +
	"SendStream\x12*.testing.testvalidate.v1.SendStreamRequest\x1a+.testing.testvalidate.v1.SendStreamResponse\"\x000\x01BUZSgithub.com/grpc-ecosystem/go-grpc-middleware/testing/testvalidate/v1;testvalidatev1b\x06proto3"

var (
	file_testing_testvalidate_v1_test_validate_proto_rawDescOnce sync.Once
	file_testing_testvalidate_v1_test_validate_proto_rawDescData []byte
)

func file_testing_testvalidate_v1_test_validate_proto_rawDescGZIP() []byte {
	file_testing_testvalidate_v1_test_validate_proto_rawDescOnce.Do(func() {
		file_testing_testvalidate_v1_test_validate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testing_testvalidate_v1_test_validate_proto_rawDesc), len(file_testing_testvalidate_v1_test_validate_proto_rawDesc)))
	})
	return file_testing_testvalidate_v1_test_validate_proto_rawDescData
}

var file_testing_testvalidate_v1_test_validate_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_testing_testvalidate_v1_test_validate_proto_goTypes = []any{
	(*SendRequest)(nil),        // 0: testing.testvalidate.v1.SendRequest
	(*SendResponse)(nil),       // 1: testing.testvalidate.v1.SendResponse
	(*SendStreamRequest)(nil),  // 2: testing.testvalidate.v1.SendStreamRequest
	(*SendStreamResponse)(nil), // 3: testing.testvalidate.v1.SendStreamResponse
}
var file_testing_testvalidate_v1_test_validate_proto_depIdxs = []int32{
	0, // 0: testing.testvalidate.v1.TestValidateService.Send:input_type -> testing.testvalidate.v1.SendRequest
	2, // 1: testing.testvalidate.v1.TestValidateService.SendStream:input_type -> testing.testvalidate.v1.SendStreamRequest
	1, // 2: testing.testvalidate.v1.TestValidateService.Send:output_type -> testing.testvalidate.v1.SendResponse
	3, // 3: testing.testvalidate.v1.TestValidateService.SendStream:output_type -> testing.testvalidate.v1.SendStreamResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testing_testvalidate_v1_test_validate_proto_init() }
func file_testing_testvalidate_v1_test_validate_proto_init() {
	if File_testing_testvalidate_v1_test_validate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testing_testvalidate_v1_test_validate_proto_rawDesc), len(file_testing_testvalidate_v1_test_validate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testing_testvalidate_v1_test_validate_proto_goTypes,
		DependencyIndexes: file_testing_testvalidate_v1_test_validate_proto_depIdxs,
		MessageInfos:      file_testing_testvalidate_v1_test_validate_proto_msgTypes,
	}.Build()
	File_testing_testvalidate_v1_test_validate_proto = out.File
	file_testing_testvalidate_v1_test_validate_proto_goTypes = nil
	file_testing_testvalidate_v1_test_validate_proto_depIdxs = nil
}
